### ISSUE TITLE
Feature 1: User can view the homepage

### ISSUE THREAD

**Issue by loganlee-lth** [loganlee-lth/Timeless#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view the homepage
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Upon entering the website's URL, the user will view the homepage. The homepage will offer an organized, intuitive interface where the user can find various featured and popular products, sections, or links to other pages. 
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Pasted image 20230802104601](https://github.com/loganlee-lth/Timeless/assets/36302145/11926a33-4f2a-4f88-b61f-f4e11245a2ab)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [x] Set up TypeScript
- [x] Set up Tailwind CSS
- [x] Create a component for the navigation bar
  - [x] Logo
  - [x] Create account
  - [x] Sign in
  - [x] Cart
  - [x] Search bar
- [x] Make the navigation bar positioned sticky
- [x] Add a hero section
- [x] Create a component for the featured products section
- [x] Create a component for the footer
- [x] Add placeholder images
- [x] Write CSS for mobile devices first
- [x] Adjust styling to fluidly adapt to desktop

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
